[package]
name = "gitbutler-user"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[lib]
doctest = false

[dependencies]
but-secret.workspace = true
but-fs = { workspace = true, features = ["legacy"] }
but-path.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }

[[test]]
name = "user"
path = "tests/mod.rs"

[dev-dependencies]
serial_test = "3.2.0"
tempfile.workspace = true
keyring.workspace = true
