[package]
name = "gitbutler-cli"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.74"

[[bin]]
name = "gitbutler-cli"
path = "src/main.rs"

[dependencies]
gitbutler-oplog.workspace = true
gitbutler-project.workspace = true
gitbutler-reference.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-command-context.workspace = true
gitbutler-branch.workspace = true
gitbutler-diff.workspace = true
gitbutler-stack.workspace = true
gix = { workspace = true, features = ["max-performance", "tracing"] }
dirs-next = "2.0.0"
clap = { version = "4.5.23", features = ["derive", "env"] }
anyhow = "1.0.95"
chrono = "0.4.39"
tracing-forest = { version = "0.1.6" }
tracing-subscriber.workspace = true
tracing.workspace = true
