[package]
name = "gitbutler-cli"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[[bin]]
name = "gitbutler-cli"
path = "src/main.rs"
doctest = false

[features]
# To help produce stable commits in test-cases.
testing = ["dep:gitbutler-commit"]

[dependencies]
but-meta = { workspace = true, features = ["legacy"] }
but-workspace.workspace = true
but-core = { workspace = true, features = ["testing"] }
but-oxidize.workspace = true
but-ctx = { workspace = true, features = ["legacy"] }

gitbutler-project.workspace = true
gitbutler-reference.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-branch.workspace = true
gitbutler-stack.workspace = true

gix = { workspace = true, features = ["max-performance", "tracing"] }
dirs-next = "2.0.0"
clap = { workspace = true, features = ["env"] }
anyhow.workspace = true
tracing-forest.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

gitbutler-commit = { workspace = true, optional = true, features = ["testing"] }
