[package]
name = "but-hunk-dependency"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
but-core.workspace = true
but-serde.workspace = true
but-ctx = { workspace = true }
but-graph.workspace = true

anyhow.workspace = true
itertools.workspace = true
serde.workspace = true
gix = { workspace = true, features = [] }

[dev-dependencies]
but-testsupport.workspace = true

insta.workspace = true
serde_json.workspace = true

[lints]
workspace = true
