[package]
name = "but-hunk-dependency"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
anyhow = "1.0.95"
itertools = "0.14.0"
serde.workspace = true
gix = { workspace = true, features = [] }
but-core.workspace = true
but-workspace.workspace = true
gitbutler-serde.workspace = true

# TODO: remove once not needed anymore
git2.workspace = true
gitbutler-repo.workspace = true
gitbutler-oxidize.workspace = true

# For `ui` module
rustc-hash = "2.1.0"
gitbutler-stack.workspace = true

[dev-dependencies]
gix-testtools.workspace = true
gitbutler-testsupport.workspace = true
gitbutler-oxidize.workspace = true
itertools = "0.14.0"
insta.workspace = true
serde_json = "1.0.138"