[package]
name = "but-workspace"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
bstr.workspace = true
git2.workspace = true
but-core.workspace = true
but-graph.workspace = true
but-rebase.workspace = true
gix = { workspace = true, features = ["worktree-mutation"] }
gitbutler-stack.workspace = true
gitbutler-command-context.workspace = true
gitbutler-error.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-cherry-pick.workspace = true
gitbutler-project.workspace = true
gitbutler-commit.workspace = true
gitbutler-repo.workspace = true
serde.workspace = true
gitbutler-serde.workspace = true
itertools.workspace = true
url = { version = "2.5.4", features = ["serde"] }
md5.workspace = true
tracing.workspace = true
# For SPMC channel
flume = "0.11.1"
tempfile.workspace = true

[dev-dependencies]
but-testsupport.workspace = true
insta = { version = "1.43.2", features = ["json"] }
but-core = { workspace = true, features = ["testing"] }
# for stable hashes in `gitbuter-` crates while we use them.
# TODO: remove once `gitbutler-repo` isn't needed anymore.
gitbutler-commit = { workspace = true, features = ["testing"] }
gitbutler-reference.workspace = true
