[package]
name = "but-workspace"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[features]
legacy = [
    "dep:but-meta",
    "dep:gitbutler-stack",
    "dep:gitbutler-command-context",
    "dep:gitbutler-cherry-pick",
    "dep:gitbutler-project",
    "dep:gitbutler-commit",
    "dep:gitbutler-repo",
]

[dependencies]
but-core.workspace = true
but-graph.workspace = true
but-rebase.workspace = true
but-error.workspace = true
but-serde.workspace = true
but-oxidize.workspace = true

but-meta = { workspace = true, features = ["legacy"], optional = true}
gitbutler-stack = { workspace = true, optional = true}
gitbutler-command-context = { workspace = true, optional = true}
gitbutler-cherry-pick = { workspace = true, optional = true}
gitbutler-project = { workspace = true, optional = true}
gitbutler-commit = { workspace = true, optional = true}
gitbutler-repo = { workspace = true, optional = true}

anyhow.workspace = true
bstr.workspace = true
git2.workspace = true
gix = { workspace = true, features = ["worktree-mutation"] }
serde.workspace = true
itertools.workspace = true
url = { version = "2.5.4", features = ["serde"] }
md5.workspace = true
tracing.workspace = true

# For SPMC channel
flume = "0.11.1"
tempfile.workspace = true

[dev-dependencies]
# We just want to test everything, with the goal that 'legacy' can one day go away.
but-workspace = { workspace = true, features = ["legacy"] }
but-meta = { workspace = true, features = ["legacy"] }
but-testsupport.workspace = true
insta = { version = "1.43.2", features = ["json"] }
but-core = { workspace = true, features = ["testing"] }
# for stable hashes in `gitbuter-` crates while we use them.
# TODO: remove once `gitbutler-repo` isn't needed anymore.
gitbutler-commit = { workspace = true, features = ["testing"] }
gitbutler-reference.workspace = true
