[package]
name = "gitbutler-user"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[dependencies]
but-secret.workspace = true
gitbutler-storage.workspace = true
but-path.workspace = true
anyhow = "1.0.100"
serde = { workspace = true, features = ["std"] }
serde_json = { version = "1.0", features = ["std", "arbitrary_precision"] }

[[test]]
name = "user"
path = "tests/mod.rs"

[dev-dependencies]
serial_test = "3.2.0"
tempfile.workspace = true
keyring.workspace = true
