[package]
name = "gitbutler-repo-actions"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-error.workspace = true
but-core.workspace = true

gitbutler-command-context.workspace = true
gitbutler-stack.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-git.workspace = true
gitbutler-project.workspace = true
gitbutler-commit.workspace = true
gitbutler-reference.workspace = true
gitbutler-repo.workspace = true
gitbutler-time.workspace = true

git2.workspace = true
serde.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "rt",
    "macros",
    "sync",
] }
log = "^0.4"
anyhow.workspace = true
tracing.workspace = true
