[package]
name = "gitbutler-filemonitor"
version = "0.0.0"
edition.workspace = true
publish = false
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing.workspace = true
gix = { workspace = true, features = ["excludes"] }

backoff = "0.4.0"
notify.workspace = true
gitbutler-notify-debouncer.path = "vendor/debouncer"
gitbutler-project.workspace = true

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
