[package]
name = "gitbutler-filemonitor"
version = "0.0.0"
edition.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing.workspace = true
gix = { workspace = true, features = ["excludes"] }

backoff.workspace = true
notify.workspace = true
gitbutler-notify-debouncer.path = "vendor/debouncer"
gitbutler-project.workspace = true

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"

[dev-dependencies]
but-testsupport.workspace = true
insta = "1.46.0"
