[package]
name = "gitbutler-workspace"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[dependencies]
anyhow.workspace = true
tracing.workspace = true
gix.workspace = true
git2.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-project.workspace = true
gitbutler-commit.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-command-context.workspace = true
gitbutler-cherry-pick.workspace = true
but-workspace.workspace = true
but-rebase.workspace = true
