[package]
name = "gitbutler-operating-modes"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
serde = { workspace = true, features = ["std"] }
git2.workspace = true
anyhow.workspace = true
gitbutler-command-context.workspace = true
