[package]
name = "but-db"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[lib]
doctest = false
test = false

[dependencies]
diesel = { version = "2.2.12", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
    "chrono",
] }
# Bundled libsqlite3 for Windows, and exactly this version to match the one of `diesel`!
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
bitflags = "2.9.4"
serde = { workspace = true, features = ["std"] }
anyhow = "1.0.100"
diesel_migrations = { version = "2.3.0", features = ["sqlite"] }
chrono = { version = "0.4.42", features = ["serde"] }
# other things
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot", "time", "sync", "macros"] }
tracing.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
