[package]
name = "but-db"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false
test = false

[dependencies]
diesel = { version = "2.3.4", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
    "chrono",
] }
# Bundled libsqlite3 for Windows, and exactly this version to match the one of `diesel`!
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
bitflags.workspace = true
serde.workspace = true
anyhow.workspace = true
diesel_migrations = { version = "2.3.1", features = ["sqlite"] }
chrono = { workspace = true, features = ["serde"] }
# other things
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot", "time", "sync", "macros"] }
tracing.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
