[package]
name = "but-github"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-settings.workspace = true
but-secret.workspace = true
but-forge-storage.workspace = true
but-error.workspace = true

serde.workspace = true
anyhow.workspace = true
gitbutler-user.workspace = true
serde_json.workspace = true
reqwest = { workspace = true, features = ["json"] }
octorust = { version = "0.10.0", default-features = false }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
http = "1"
