[package]
name = "but-github"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license-file = "../../LICENSE.md"
description = "The GitButler GitHub integration"
authors.workspace = true
readme = "../../README.md"
publish = false
rust-version.workspace = true

[features]
export-ts = ["dep:ts-rs"]
export-schema = ["dep:schemars"]

[lib]
doctest = false

[dependencies]
but-settings.workspace = true
but-secret.workspace = true
but-forge-storage.workspace = true
but-error.workspace = true

serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
reqwest = { workspace = true, features = ["json"] }
ts-rs = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }

[lints]
workspace = true
