[package]
name = "but-github"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors.workspace = true
readme = "../../README.md"
publish = false
rust-version.workspace = true

[lib]
doctest = false

[features]
legacy = ["dep:gitbutler-user"]

[dependencies]
but-settings.workspace = true
but-secret.workspace = true
but-forge-storage.workspace = true
but-error.workspace = true

gitbutler-user = { workspace = true, optional = true }

serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
reqwest = { workspace = true, features = ["json"] }
octorust = { version = "0.10.0", default-features = false }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
http = "1"
