[package]
name = "gitbutler-project"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
anyhow = "1.0.100"
parking_lot = { workspace = true, features = ["arc_lock"] }
serde = { workspace = true, features = ["std"] }
serde_json = { version = "1.0", features = ["std", "arbitrary_precision"] }
gitbutler-error.workspace = true
but-path.workspace = true
gitbutler-serde.workspace = true
gitbutler-id.workspace = true
gitbutler-storage.workspace = true
but-core.workspace = true
git2.workspace = true
gix = { workspace = true, features = ["dirwalk", "credentials", "parallel"] }
uuid.workspace = true
strum = { version = "0.27", features = ["derive"] }
tracing.workspace = true
resolve-path = "0.1.0"

# for locking
fslock = "0.2.1"

[dev-dependencies]
gitbutler-testsupport.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "rt", "macros"] }
