[package]
name = "gitbutler-workspace"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[lib]
doctest = false

[dependencies]
but-oxidize.workspace = true
but-core.workspace = true
but-rebase.workspace = true
but-ctx.workspace = true

gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-commit.workspace = true
gitbutler-cherry-pick.workspace = true

anyhow.workspace = true
gix.workspace = true
git2.workspace = true
