[package]
name = "but-cherry-apply"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-core.workspace = true
but-workspace = { workspace = true, features = ["legacy"] }
but-rebase.workspace = true
but-meta = { workspace = true, features = ["legacy"] }
but-oxidize.workspace = true
but-ctx.workspace = true

gitbutler-branch-actions.workspace = true
gitbutler-stack.workspace = true
gitbutler-workspace.workspace = true

anyhow.workspace = true
gix.workspace = true
serde.workspace = true

[dev-dependencies]
but-oxidize.workspace = true

gitbutler-testsupport.workspace = true

gix-testtools.workspace = true
