[package]
name = "but-gerrit"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false
test = false

[dependencies]
but-core.workspace = true
but-db.workspace = true
but-ctx.workspace = true

gitbutler-commit.workspace = true

sha-1 = "0.10.1"
uuid.workspace = true
anyhow.workspace = true
bstr.workspace = true
chrono.workspace = true
serde.workspace = true
gix = { workspace = true }
