[package]
name = "but-secret"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[dependencies]
anyhow = "1.0.100"
tracing.workspace = true
serde = { workspace = true, features = ["std"]}
gix = { workspace = true, features = ["dirwalk", "credentials", "parallel"] }
gitbutler-error.workspace = true
keyring.workspace = true

[[test]]
name="secret"
path = "tests/mod.rs"

[dev-dependencies]
