[package]
name = "but-testsupport"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[features]
snapbox = ["dep:snapbox"]

[dependencies]
but-graph.workspace = true
but-core.workspace = true

gix-testtools.workspace = true

gix.workspace = true
anyhow.workspace = true
termtree = "0.5.1"
regex = { workspace = true }
snapbox = { workspace = true, optional = true }

[dev-dependencies]
