[package]
name = "but-schemars"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[features]
legacy = []

[dependencies]
schemars.workspace = true

[lints]
workspace = true
