[package]
name = "gitbutler-repo"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
gitbutler-core.workspace = true
anyhow = "1.0.86"
bstr = "1.9.1"
