[package]
name = "gitbutler-repo"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
gitbutler-core.workspace = true
anyhow = "1.0.86"
bstr = "1.9.1"
tokio = { workspace = true, features = [ "rt-multi-thread", "rt", "macros" ] }
gitbutler-git.workspace = true
tracing = "0.1.40"
tempfile = "3.10"
thiserror.workspace = true
resolve-path = "0.1.0"
gitbutler-command-context.workspace = true
gitbutler-config.workspace = true
gitbutler-project.workspace = true

[[test]]
name="repo"
path = "tests/mod.rs"

[dev-dependencies]
gitbutler-testsupport.workspace = true
gitbutler-user.workspace = true
serde_json = { version = "1.0", features = [ "std", "arbitrary_precision" ] }
