[package]
name = "gitbutler-sync"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
but-error.workspace = true
but-oxidize.workspace = true
but-ctx.workspace = true

gitbutler-oplog.workspace = true
gitbutler-project.workspace = true
gitbutler-user.workspace = true
gitbutler-reference.workspace = true
gitbutler-url.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-commit.workspace = true

anyhow.workspace = true
tracing.workspace = true
itertools.workspace = true
git2.workspace = true
gix.workspace = true
rand = "0.9"
