[package]
name = "gitbutler-sync"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
anyhow = "1.0.86"
tracing = "0.1.40"
itertools = "0.13"
git2.workspace = true
gitbutler-core.workspace = true
