[package]
name = "gitbutler-sync"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
anyhow = "1.0.99"
tracing.workspace = true
itertools = "0.14"
git2.workspace = true
gix.workspace = true
gitbutler-oplog.workspace = true
gitbutler-command-context.workspace = true
gitbutler-project.workspace = true
gitbutler-user.workspace = true
gitbutler-branch.workspace = true
gitbutler-reference.workspace = true
gitbutler-error.workspace = true
gitbutler-id.workspace = true
gitbutler-url.workspace = true
gitbutler-stack.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-repo.workspace = true
gitbutler-commit.workspace = true
uuid.workspace = true
rand = "0.9"
