[package]
name = "but-llm"
version = "0.1.0"
repository.workspace = true
authors.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
description = "LLM client interface"

[dependencies]
but-secret.workspace = true
but-tools.workspace = true
async-openai.workspace = true
serde.workspace = true
futures = "0.3.31"
tracing.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "io-std"] }
schemars.workspace = true
serde_json.workspace = true
anyhow.workspace = true
strum = { version = "0.27", features = ["derive"] }
gix.workspace = true
reqwest.workspace = true

[lints]
workspace = true
