[package]
name = "but-rebase"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
gix = { workspace = true, features = ["revision", "merge"]}
anyhow.workspace = true
tracing.workspace = true
but-core.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-error.workspace = true
bstr.workspace = true
tempfile.workspace = true
serde = { version = "1.0.218", features = ["derive"] }
toml.workspace = true

[dev-dependencies]
but-testsupport.workspace = true
insta = "1.42.1"
but-core = { workspace = true, features = ["testing"] }
