[package]
name = "but-rebase"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[lib]
doctest = false

[dependencies]
gix.workspace = true
anyhow.workspace = true
tracing.workspace = true
but-core.workspace = true
gitbutler-repo.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-error.workspace = true
bstr.workspace = true
git2.workspace = true
tempfile.workspace = true

[dev-dependencies]
gix-testtools.workspace = true
