[package]
name = "but-rebase"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-core.workspace = true
but-gerrit.workspace = true
but-error.workspace = true
but-oxidize.workspace = true
but-graph.workspace = true

gix = { workspace = true, features = ["revision", "merge"] }
anyhow.workspace = true
tracing.workspace = true
bstr.workspace = true
tempfile.workspace = true
serde.workspace = true
toml.workspace = true
petgraph.workspace = true

[dev-dependencies]
but-testsupport.workspace = true
insta = "1.43.2"
but-core = { workspace = true, features = ["testing"] }
