[package]
name = "but-settings"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
but-path.workspace = true
but-fs.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
serde_json_lenient.workspace = true
notify.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[[test]]
name = "settings"
path = "tests/mod.rs"

[dev-dependencies]
