[package]
name = "but-settings"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
anyhow = "1.0.100"
serde = { workspace = true, features = ["std"] }
serde_json = { version = "1.0", features = ["std", "arbitrary_precision"] }
serde_json_lenient.workspace = true
gitbutler-fs.workspace = true
notify = { version = "8.2.0" }
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
dirs.workspace = true
but-path.workspace = true

[[test]]
name = "settings"
path = "tests/mod.rs"

[dev-dependencies]
