[package]
name = "gitbutler-config"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
gix.workspace = true
anyhow = "1.0.95"
tracing.workspace = true
serde = { workspace = true, features = ["std"]}
gitbutler-project.workspace = true
