[package]
name = "gitbutler-git"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.89"
[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "gitbutler-git-askpass"
path = "src/bin/askpass.rs"
test = false

[[bin]]
name = "gitbutler-git-setsid"
path = "src/bin/setsid.rs"
test = false

[features]
default = ["serde", "tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]
## a flag that is needed for integration tests that run this code to work.
test-askpass-path = []
## a flag to indicate benchmarks are run
benches = []

[dependencies]
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = [
    "process",
    "time",
    "io-util",
    "net",
    "fs",
] }
uuid = { workspace = true, features = ["fast-rng"] }
rand.workspace = true
futures.workspace = true
sysinfo = "0.37.1"
gix.workspace = true
gitbutler-error.workspace = true

[target."cfg(unix)".dependencies]
nix = { version = "0.30.0", features = ["process", "socket", "user"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.62.0", features = [
    "Win32",
    "Win32_System",
    "Win32_System_Pipes",
    "Win32_Storage",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Threading",
] }
tokio = { workspace = true, optional = true, features = ["sync", "rt"] }
# TODO: use released version once published.
file-id = { git = "https://github.com/notify-rs/notify", rev = "978fe719b066a8ce76b9a9d346546b1569eecfb6", version = "0.2.3" }

[dev-dependencies]
assert_cmd = "2.0.17"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
