[package]
name = "gitbutler-commit"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[features]
# Set when building in test-mode to enable features that help with generating repeatable tests.
testing = []

[dependencies]
git2.workspace = true
gix.workspace = true
bstr.workspace = true
uuid.workspace = true
