[package]
name = "but-serde"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[features]
legacy = ["dep:git2"]

[dependencies]
git2 = { workspace = true, optional = true }

gix.workspace = true
serde.workspace = true
bstr.workspace = true
