[package]
name = "gitbutler-cherry-pick"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
gitbutler-commit.workspace = true
git2.workspace = true
gitbutler-oxidize.workspace = true
gix.workspace = true
anyhow.workspace = true
