[package]
name = "gitbutler-cherry-pick"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
but-core.workspace = true
but-oxidize.workspace = true

gitbutler-commit.workspace = true

git2.workspace = true
gix.workspace = true
anyhow.workspace = true
tracing.workspace = true
