[package]
name = "gitbutler-diff"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true
autotests = false

[lib]
doctest = false

[dependencies]
but-serde = { workspace = true, features = ["legacy"] }
but-ctx.workspace = true

gitbutler-cherry-pick.workspace = true

git2.workspace = true
bstr.workspace = true
md5.workspace = true
anyhow.workspace = true
hex = "0.4.3"
tracing.workspace = true
diffy = "0.4.0"
serde.workspace = true

[[test]]
name = "diff"
path = "tests/mod.rs"
