[build]
rustflags = ["--cfg", "tokio_unstable"]
target-dir = "target" # Needs to be the default directory as this assumption is used by some of the TypeScript files

 [alias]
 lint = "clippy --workspace --all-targets -- -D warnings"
