[package]
name = "but-tools"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[lib]
doctest = false
test = false

[dependencies]
async-openai = "0.29.3"
tokio = { workspace = true, features = ["rt-multi-thread", "io-std"] }
serde_json = "1.0.145"
futures = "0.3.31"
anyhow = "1.0.100"
schemars = "0.9.0"
serde = { workspace = true, features = ["std"] }
serde-error = "0.1.3"
bstr.workspace = true
gix.workspace = true
but-core.workspace = true
but-workspace.workspace = true
gitbutler-command-context.workspace = true
gitbutler-oplog.workspace = true
but-graph.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-branch.workspace = true
gitbutler-project.workspace = true
gitbutler-stack.workspace = true
gitbutler-serde.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-reference.workspace = true
but-hunk-dependency.workspace = true
but-hunk-assignment.workspace = true