[package]
name = "gitbutler-commit"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
gix.workspace = true
bstr.workspace = true
uuid.workspace = true
