[package]
name = "gitbutler-serde"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
git2.workspace = true
gix.workspace = true
serde = { workspace = true, features = ["std"] }
bstr.workspace = true
gitbutler-oxidize.workspace = true
