[package]
name = "but-hunk-assignment"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-core.workspace = true
but-hunk-dependency.workspace = true
but-db.workspace = true

gitbutler-command-context.workspace = true
gitbutler-stack.workspace = true

anyhow.workspace = true
itertools.workspace = true
serde.workspace = true
serde-error = "0.1.3"
serde_json.workspace = true
uuid.workspace = true
bstr.workspace = true
tracing.workspace = true

[dev-dependencies]
uuid.workspace = true
