[package]
name = "but-hunk-assignment"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false


[lib]
doctest = false

[dependencies]
anyhow = "1.0.99"
itertools.workspace = true
serde.workspace = true
serde-error = "0.1.3"
gix = { workspace = true, features = [] }
but-workspace.workspace = true
but-core.workspace = true
but-hunk-dependency.workspace = true
but-db.workspace = true
serde_json = "1.0.143"
uuid.workspace = true
gitbutler-command-context.workspace = true
gitbutler-stack.workspace = true
gitbutler-fs.workspace = true
bstr.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
uuid.workspace = true
