[package]
name = "but-hunk-assignment"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[features]
export-ts = ["dep:ts-rs", "but-core/export-ts"]

[dependencies]
but-core.workspace = true
but-graph.workspace = true
but-hunk-dependency.workspace = true
but-db.workspace = true
but-serde.workspace = true

gix.workspace = true

anyhow.workspace = true
itertools.workspace = true
serde.workspace = true
serde-error = "0.1.3"
serde_json.workspace = true
uuid.workspace = true
bstr.workspace = true
tracing.workspace = true
ts-rs = { workspace = true, optional = true }

[dev-dependencies]
uuid.workspace = true
