[package]
name = "but-forge-storage"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"
publish = false
rust-version = "1.89"
description = "Store and retrieve information about forges"

[lib]
doctest = false

[dependencies]
but-secret.workspace = true
but-fs = { workspace = true, features = ["legacy"] }

serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
