[package]
name = "but-forge-storage"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license-file = "../../LICENSE.md"
authors.workspace = true
readme = "../../README.md"
publish = false
rust-version.workspace = true
description = "Store and retrieve information about forges"

[lib]
doctest = false

[dependencies]
but-secret.workspace = true
but-fs = { workspace = true, features = ["legacy"] }

serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
