[package]
name = "but-rules"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false


[lib]
doctest = false

[dependencies]
anyhow = "1.0.99"
itertools.workspace = true
serde.workspace = true
regex = "1.11.2"
gix = { workspace = true }
chrono = { version = "0.4.41", features = [] }
serde_regex = "1.1.0"
serde_json = "1.0.143"
gitbutler-command-context.workspace = true
but-db.workspace = true
but-core.workspace = true
but-hunk-assignment.workspace = true
but-graph.workspace = true
but-workspace.workspace = true
but-hunk-dependency.workspace = true
gitbutler-stack.workspace = true
gitbutler-project.workspace = true
gitbutler-branch.workspace = true
gitbutler-branch-actions.workspace = true
uuid.workspace = true
