[package]
name = "but-rules"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-db.workspace = true
but-core.workspace = true
but-hunk-assignment.workspace = true
but-graph = { workspace = true, features = ["legacy"] }
but-meta = { workspace = true, features = ["legacy"] }
but-workspace = { workspace = true, features = ["legacy"] }
but-hunk-dependency.workspace = true

gitbutler-command-context.workspace = true
gitbutler-stack.workspace = true
gitbutler-branch.workspace = true
gitbutler-branch-actions.workspace = true

anyhow.workspace = true
itertools.workspace = true
serde.workspace = true
regex = { workspace = true, features = ["perf"] }
gix = { workspace = true }
chrono.workspace = true
serde_regex = "1.1.0"
serde_json.workspace = true
uuid.workspace = true
