[package]
name = "gitbutler-git"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "gitbutler-git-askpass"
path = "src/bin/askpass.rs"
test = false

[[bin]]
name = "gitbutler-git-setsid"
path = "src/bin/setsid.rs"
test = false

[features]
default = ["serde", "tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]
## a flag that is needed for integration tests that run this code to work.
test-askpass-path = []
## a flag to indicate benchmarks are run
benches = []

[dependencies]
thiserror.workspace = true
serde = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = [
    "process",
    "time",
    "io-util",
    "net",
    "fs",
] }
uuid = { workspace = true, features = ["fast-rng"] }
rand = "0.8.5"
futures.workspace = true
sysinfo = "0.32.1"
gix-path = "0.10.11"

[target."cfg(unix)".dependencies]
nix = { version = "0.29.0", features = ["process", "socket", "user"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.58.0", features = [
    "Win32",
    "Win32_System",
    "Win32_System_Pipes",
    "Win32_Storage",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Threading",
] }
tokio = { workspace = true, optional = true, features = ["sync"] }

[dev-dependencies]
assert_cmd = "2.0.15"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
