[package]
name = "gitbutler-git"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "gitbutler-git-askpass"
path = "src/bin/askpass.rs"

[[bin]]
name = "gitbutler-git-setsid"
path = "src/bin/setsid.rs"

[features]
default = ["serde", "tokio"]
serde = ["dep:serde"]
tokio = ["dep:tokio"]

[dependencies]
thiserror.workspace = true
serde = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["process", "rt", "process", "time", "io-util", "net", "fs", "sync"] }
rand = "0.8.5"
futures = "0.3.30"
sysinfo = "0.30.5"

[target."cfg(unix)".dependencies]
nix = { version = "0.28.0", features = ["process", "socket", "user"] }

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.9", features = ["winbase", "namedpipeapi"] }
# synchronous named pipes for the askpass utility
windows-named-pipe = "0.1.0"

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
