[package]
name = "gitbutler-forge"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
serde = { workspace = true, features = ["std"] }
anyhow = "1.0.100"
gitbutler-fs.workspace = true