[package]
name = "gitbutler-testsupport"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
doctest = false
test = false

[dependencies]
anyhow = "1.0.100"
once_cell = "1.20"
git2.workspace = true
tempfile.workspace = true
keyring.workspace = true
serde_json = "1.0"
gix-testtools.workspace = true
gix.workspace = true
parking_lot.workspace = true
gitbutler-branch-actions = { path = "../gitbutler-branch-actions" }
gitbutler-repo = { path = "../gitbutler-repo" }
gitbutler-command-context.workspace = true
gitbutler-project.workspace = true
but-graph.workspace = true
but-workspace.workspace = true
gitbutler-user.workspace = true
gitbutler-reference.workspace = true
gitbutler-storage.workspace = true
gitbutler-url.workspace = true
gitbutler-stack.workspace = true
but-settings.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-commit.workspace = true
termtree = "0.5.1"
uuid.workspace = true
