[package]
name = "gitbutler-testsupport"
version = "0.0.0"
edition.workspace = true
publish = false
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false
test = false

[dependencies]
but-core.workspace = true
but-settings.workspace = true
but-oxidize.workspace = true
but-meta = {workspace = true, features = ["legacy"]}
but-workspace.workspace = true
but-fs = {workspace = true, features = ["legacy"]}
but-ctx.workspace = true

gitbutler-branch-actions = { path = "../gitbutler-branch-actions" }
gitbutler-repo = { path = "../gitbutler-repo" }
gitbutler-project.workspace = true
gitbutler-user.workspace = true
gitbutler-reference.workspace = true
gitbutler-url.workspace = true
gitbutler-stack.workspace = true
gitbutler-commit.workspace = true

anyhow.workspace = true
once_cell = "1.20"
git2.workspace = true
tempfile.workspace = true
keyring.workspace = true
serde_json.workspace = true
gix-testtools.workspace = true
gix.workspace = true
parking_lot.workspace = true
termtree = "0.5.1"
uuid.workspace = true
