[package]
name = "gitbutler-hunk-dependency"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[lib]
doctest = false

[dependencies]
but-serde = { workspace = true, features = ["legacy"]}

gitbutler-diff.workspace = true
gitbutler-stack.workspace = true

anyhow.workspace = true
git2.workspace = true
itertools.workspace = true
serde.workspace = true

[[test]]
name = "hunk-dependency"
path = "tests/mod.rs"
