[package]
name = "but-worktrees"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
but-workspace.workspace = true
but-meta = { workspace = true, features = ["legacy"] }
but-status.workspace = true
but-rebase.workspace = true
but-core.workspace = true
but-oxidize.workspace = true
but-ctx.workspace = true

gitbutler-project.workspace = true
gitbutler-stack.workspace = true
gitbutler-workspace.workspace = true
gitbutler-branch-actions.workspace = true

anyhow.workspace = true
gix.workspace = true
serde.workspace = true
uuid.workspace = true
bstr.workspace = true
tracing.workspace = true

[dev-dependencies]
but-oxidize.workspace = true

gitbutler-branch-actions.workspace = true
gitbutler-testsupport.workspace = true

gix-testtools.workspace = true
insta.workspace = true
but-testsupport.workspace = true
