[package]
name = "but-meta"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
description = "Implementation for but-core traits to obtain metadata on Git entities"
publish = false
rust-version.workspace = true

[lib]
doctest = false
test = false

[features]
legacy = [
    "dep:but-serde",
    "dep:but-graph",
    "dep:gitbutler-reference",
    "dep:tracing",
    "dep:itertools",
    "dep:toml",
    "dep:serde",
    "dep:md5",
    "dep:hex",
    "dep:gix",
]

[dependencies]
but-core.workspace = true
but-serde = { workspace = true, optional = true }
but-graph = { workspace = true, optional = true }

gitbutler-reference = {workspace = true, optional = true}

bstr.workspace = true
anyhow.workspace = true

gix = { workspace = true, features = ["revision"], optional = true }
tracing = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
md5 = { workspace = true, optional = true }
hex = { version = "0.4.3", optional = true }

[dev-dependencies]
but-meta = {workspace = true, features = ["legacy"] }
but-testsupport.workspace = true

insta = "1.44.3"

