[package]
name = "gitbutler-command-context"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-db.workspace = true
but-settings.workspace = true
but-meta = { workspace = true, features = ["legacy"] }
but-graph.workspace = true

gitbutler-project.workspace = true

anyhow.workspace = true
git2.workspace = true
gix.workspace = true
tracing.workspace = true
bstr = "1.12.1"
