[package]
name = "gitbutler-oplog"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[lib]
doctest = false

[dependencies]
but-graph.workspace = true
but-serde = { workspace = true, features = ["legacy"]}
but-core.workspace = true
but-workspace.workspace = true

gitbutler-command-context.workspace = true
gitbutler-project.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-branch.workspace = true
gitbutler-fs.workspace = true
gitbutler-reference.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true

anyhow.workspace = true
git2.workspace = true
serde.workspace = true
itertools.workspace = true
strum = { version = "0.27", features = ["derive"] }
tracing.workspace = true
gix = { workspace = true, features = ["dirwalk", "credentials", "parallel"] }
toml.workspace = true

[[test]]
name = "oplog"
path = "tests/mod.rs"

[dev-dependencies]
pretty_assertions = "1.4"
tempfile.workspace = true
