[package]
name = "gitbutler-user"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
gitbutler-secret.workspace = true
gitbutler-storage.workspace = true
anyhow = "1.0.91"
serde = { workspace = true, features = ["std"]}
serde_json = { version = "1.0", features = [ "std", "arbitrary_precision" ] }

[[test]]
name="user"
path = "tests/mod.rs"

[dev-dependencies]
serial_test = "3.1.1"
tempfile = "3.13"
keyring.workspace = true
