[package]
name = "but-api"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"
publish = false
rust-version = "1.89"

[lib]
doctest = false

[features]
tauri = ["dep:tauri"]

[dependencies]
but-settings.workspace = true
but-github.workspace = true
but-secret.workspace = true
but-workspace = { workspace = true, features = ["legacy"] }
but-worktrees.workspace = true
but-core.workspace = true
but-gerrit.workspace = true
but-hunk-assignment.workspace = true
but-action.workspace = true
but-api-macros.workspace = true
but-rebase.workspace = true
but-serde.workspace = true
but-graph.workspace = true
but-meta = { workspace = true, features = ["legacy"] }
but-claude.workspace = true
but-broadcaster.workspace = true
but-cherry-apply.workspace = true
but-hunk-dependency.workspace = true
but-path.workspace = true
but-forge-storage.workspace = true
but-feedback.workspace = true
but-error.workspace = true
but-rules.workspace = true
but-oxidize.workspace = true

gitbutler-user.workspace = true
gitbutler-project.workspace = true
gitbutler-branch.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-commit.workspace = true
gitbutler-command-context.workspace = true
gitbutler-reference.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-repo-actions.workspace = true
gitbutler-edit-mode.workspace = true
gitbutler-operating-modes.workspace = true
gitbutler-sync.workspace = true
gitbutler-oplog.workspace = true
gitbutler-forge.workspace = true

tauri = { version = "^2.9.2", features = ["unstable"], optional = true } # For the #[tauri::command(async)] macro only

serde.workspace = true
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
serde-error = "0.1.3"
gix = { workspace = true, features = ["worktree-mutation" ] }
git2.workspace = true
open.workspace = true
url = "2.5"
uuid.workspace = true
