[package]
name = "but-api"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"

[features]

[dependencies]
serde.workspace = true
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
    "std",
] }
tokio = { workspace = true, features = ["full"] }
tokio-util = "0.7.15"
dirs.workspace = true
bstr.workspace = true
anyhow.workspace = true
serde_json = "1.0.140"
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }

but-settings.workspace = true
gitbutler-user.workspace = true
gitbutler-project.workspace = true
gitbutler-secret.workspace = true
but-workspace.workspace = true
but-core.workspace = true
but-hunk-assignment.workspace = true
gitbutler-branch.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-command-context.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-reference.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-repo-actions.workspace = true
gitbutler-edit-mode.workspace = true
gitbutler-operating-modes.workspace = true
gitbutler-sync.workspace = true
but-graph.workspace = true
gitbutler-oplog.workspace = true
but-hunk-dependency.workspace = true
serde-error = "0.1.3"
gix = { workspace = true, features = [
    "worktree-mutation",
    "blocking-http-transport-curl",
] }
git2.workspace = true
gitbutler-feedback.workspace = true
gitbutler-error.workspace = true
gitbutler-diff.workspace = true
gitbutler-watcher.workspace = true
but-rules.workspace = true
but-action.workspace = true
reqwest = { version = "0.12", features = ["json"] }
gitbutler-forge.workspace = true
open = "5.3"
url = "2.5"
gitbutler-id.workspace = true
uuid.workspace = true
