[package]
name = "but-api"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"
publish = false
rust-version = "1.89"

[features]
tauri = ["dep:tauri"]

[dependencies]
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
tauri = { version = "^2.7.0", features = ["unstable"], optional = true } # For the #[tauri::command(async)] macro only

but-settings.workspace = true
but-github.workspace = true
gitbutler-user.workspace = true
gitbutler-project.workspace = true
but-secret.workspace = true
but-workspace.workspace = true
but-worktrees.workspace = true
but-core.workspace = true
but-gerrit.workspace = true
but-hunk-assignment.workspace = true
but-action.workspace = true
but-api-macros.workspace = true
but-rebase.workspace = true
gitbutler-serde.workspace = true
gitbutler-branch.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-commit.workspace = true
gitbutler-command-context.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-reference.workspace = true
gitbutler-stack.workspace = true
gitbutler-repo.workspace = true
gitbutler-repo-actions.workspace = true
gitbutler-edit-mode.workspace = true
gitbutler-operating-modes.workspace = true
gitbutler-sync.workspace = true
but-graph.workspace = true
but-claude.workspace = true
but-broadcaster.workspace = true
but-cherry-apply.workspace = true
gitbutler-oplog.workspace = true
but-hunk-dependency.workspace = true
but-path.workspace = true
but-forge-storage.workspace = true
serde-error = "0.1.3"
gix = { workspace = true, features = ["worktree-mutation" ] }
git2.workspace = true
but-feedback.workspace = true
gitbutler-error.workspace = true
but-rules.workspace = true
gitbutler-forge.workspace = true
open = "5.3"
url = "2.5"
gitbutler-id.workspace = true
uuid.workspace = true
