[package]
name = "gitbutler-project"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-error.workspace = true
but-path.workspace = true
but-serde =  { workspace = true, features = ["legacy"] }
but-core.workspace = true

gitbutler-storage.workspace = true
gitbutler-forge.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
git2.workspace = true
gix = { workspace = true, features = [
    "dirwalk",
    "credentials",
    "parallel",
    "blocking-http-transport-reqwest-rust-tls",
] }
strum = { version = "0.27", features = ["derive"] }
tracing.workspace = true
resolve-path = "0.1.0"

[dev-dependencies]
gitbutler-testsupport.workspace = true
tempfile.workspace = true
insta.workspace = true
