[package]
name = "gitbutler-edit-mode"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
but-workspace.workspace = true
but-rebase.workspace = true
but-core.workspace = true
but-oxidize.workspace = true

gitbutler-commit.workspace = true
gitbutler-repo.workspace = true
but-ctx.workspace = true
gitbutler-operating-modes.workspace = true
gitbutler-project.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-oplog.workspace = true
gitbutler-stack.workspace = true
gitbutler-cherry-pick.workspace = true
gitbutler-workspace.workspace = true

git2.workspace = true
gix.workspace = true
anyhow.workspace = true
bstr.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
gitbutler-testsupport.workspace = true

tempfile.workspace = true
