name: Web App Tests
on:
  push:
    branches:
      - master
    paths:
      - 'apps/web/**'
      - 'scripts/install.sh'
      - '.github/workflows/test-web.yml'
  pull_request:
    paths:
      - 'apps/web/**'
      - 'scripts/install.sh'
      - '.github/workflows/test-web.yml'

jobs:
  test:
    name: web-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup node environment
        uses: ./.github/actions/init-env-node

      - name: Run unit tests
        working-directory: apps/web
        run: pnpm test

      - name: Install Playwright browsers
        working-directory: apps/web
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright e2e tests
        working-directory: apps/web
        run: pnpm test:e2e:web

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 7
