name: Client Frontend Integration Tests

on:
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: false
        description: Target SHA
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - uses: actions/checkout@v5
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.sha }}
      - name: Setup node environment
        uses: ./.github/actions/init-env-node
      - name: Build SvelteKit
        run: pnpm build:desktop
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Set up Cypress binary cache
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
      - if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: pnpm --dir apps/desktop cy:install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          cache-key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
          start: pnpm --dir apps/desktop preview
          wait-on: 'http://localhost:1420'
          command: pnpm --dir apps/desktop cy:ci
